---

- name: Install build dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - libssl-dev
    - libffi-dev
    - zlib1g-dev

- name: Create ansible specific folder
  file:
    path: /usr/local/ansible
    state: directory

- name: download latest Python (3.7.4)
  get_url:
    url: https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tgz
    dest: /usr/local/ansible/
    checksum: md5:68111671e5b2db4aef7b9ab01bf0f9be

- name: Extract Python into /usr/local/ansible/
  unarchive:
    src: /usr/local/ansible/Python-3.7.4.tgz
    dest: /usr/local/ansible/
    remote_src: yes

- name: Compile Python 1/3 (configure)
  shell: /usr/local/ansible/Python-3.7.4/configure --prefix=/usr/local/ansible/compiled-python
  args:
    chdir: /usr/local/ansible/Python-3.7.4

- name: Compile Python 2/3 (make)
  shell: make
  args:
    chdir: /usr/local/ansible/Python-3.7.4

- name: Compile Python 1/3 (make install)
  shell: make install
  args:
    chdir: /usr/local/ansible/Python-3.7.4

- name: install latest pip
  pip:
    name: pip
    state: latest
    virtualenv: /usr/local/ansible/ansible-venv
    virtualenv_command: /usr/local/ansible/compiled-python/bin/pyvenv

- name: Remove build dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - libssl-dev
    - libffi-dev
    - zlib1g-dev
...
